<!DOCTYPE html>
<html lang="en">
    <head>
    	<title>StudyHive</title>
    	<meta charset="UTF-8" />
        <meta name="description" content="Your Home Away From Home" />
        <meta name="keywords" content="StudyHive" />
        <meta name="author" content="StudyHive" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" type="image/png" href="./images/logo.png" />
    	<!-- jQuery -->
    	<script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
    	<!-- Bootstrap -->
    	<link rel="stylesheet" href="https://bootswatch.com/5/cosmo/bootstrap.min.css"/>
    	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js"></script>
    	<!-- Study Hive CSS -->
    	<link href="./css/index.css" rel="stylesheet" type="text/css" />
    	<link href="./css/fonts.css" rel="stylesheet" type="text/css" />
    	<link href="./css/landingpage.css" rel="stylesheet" type="text/css" />
    	<!-- SweetAlert2 -->
    	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    	<!-- Google Fonts -->
    	<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    	<!-- Font Awesome 6 Pro -->
		<link href="https://cdn.jsdelivr.net/gh/duyplus/fontawesome-pro/css/all.min.css" rel="stylesheet" type="text/css" />
    </head>
    <body style="background:#e1e6e9;">
        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background:#fff!important;">
    		<div class="container">
                 <a class="navbar-brand" href="#" style="font-family: 'Poppins', sans-serif;">
                    <img src="./images/logo.png" style="width: 30px; height: 30px; margin-right: 10px; margin-top: -10px;">
                    Study<font style="color:#007f7f;">Hive</font>
                </a>
    		</div>
    	</nav>
    	<section id="intro">
    	    <div class="intro2">
    	        <div class="intro3">
                    <div class="container-lg">
                        <div class="row g-4 justify-content-center align-items-center">
                            <div class="col-md-5 text-center text-md-start">
                                        <h1 style="user-select: none;">
                                            <div class="display-2" style="font-family: 'Poppins', sans-serif; font-weight: 600; color: #363e41!important;">Study<font style="color: #007f7f;">Hive</font></div>
                                            <div class="display-6 text-muted" style="font-family: 'Poppins', sans-serif; font-weight: 600; font-size: 34px; color: #363e41!important;">Your Home Away From Home</div>
                                        </h1>
                                        <p class="lead my-4 text-muted" style="font-family: 'Poppins', sans-serif; font-weight: 400; font-size: 17px; color: #363e41!important; user-select: none;">
                                            Discover convenience, comfort, and community, all at your fingertips. Simplify your accommodation search with StudyHive.
                                        </p>

                                <a href="https://drive.google.com/file/d/1MVAcMlGin9yJ20kD4SGqlAGBMPP97NKI/view?usp=drive_link">
                                    <img src="./images/apk.png" style="width: 200px;"/>
                                </a>
                            </div>
                            <div class="col-md-5 text-center d-none d-md-block">
                                <img
                                    src="./images/studyhive_splash.png"
                                    class="img-fluid"
                                />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section id="about">
            <div class="container">
                <div class="row">
                    <div class="col-12 col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4">
                        <img src="./images/logo_white.png" class="img-fluid" style="padding: 50px;"/>
                    </div>
                    <div class="col-12 col-xs-12 col-sm-12 col-md-8 col-lg-8 col-xl-8" style="user-select:none;">
                       <h1 style="color:#fff;font-weight: 600; font-family: 'Poppins', sans-serif;">About StudyHive</h1>
                       <p style="color:#fff;font-weight: 500; font-family: 'Poppins', sans-serif;">
                            StudyHive believes that finding the right accommodation is crucial for students to thrive academically and personally. We aim to provide a user-friendly platform that streamlines the entire process, making it easier, faster, and more efficient.<br/><br/>
    
                            <span style="font-size: 22px; font-weight: 600;">For Students:</span><br/>
                            Our application provides various functionalities that enable students to discover a diverse selection of housing choices tailored to their preferences. Whether you're looking for a cozy apartment, a shared house, or a dormitory, StudyHive got you covered.<br/><br/>
                            
                            <span style="font-size: 22px; font-weight: 600;">For Student Accommodation Owners</span><br/>
                            StudyHive is not just for students; it's also a platform for business owners or landlords to connect with potential tenants. If you own a student accommodation facility, our app provides you with a convenient and efficient way to post and manage your listings, and interact with interested students.
                        </p>
                    </div>
                </div>
            </div>
        </section>
        <section id="content">
            <div class="container">
                <div class="row mb-5">
                    <div class="col-12">
                        <h1 style="font-weight: 600;text-align:center;user-select:none; font-family: 'Poppins', sans-serif;">Our <font style="color:#007f7f;">Services</font></h1>
                    </div>
                </div>
                <div class="row px-5">
                    <div class="col-12 col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4" style="font-family: 'Poppins', sans-serif;">
                        <div class="services-box">
                            <i class="fa-solid fa-house"></i>
                            Student Accommodation
                        </div>
                    </div>
                    <div class="col-12 col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4" style="font-family: 'Poppins', sans-serif;">
                        <div class="services-box">
                            <i class="fa-solid fa-list"></i>
                            Listing Management
                        </div>
                    </div>
                    <div class="col-12 col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4" style="font-family: 'Poppins', sans-serif;">
                        <div class="services-box">
                            <i class="fa-solid fa-credit-card"></i>
                            Easy Payment
                        </div>
                    </div>
                    <div class="col-12 col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4" style="font-family: 'Poppins', sans-serif;">
                        <div class="services-box">
                            <i class="fa-solid fa-ballot-check"></i>
                            Choose your type
                        </div>
                    </div>
                    <div class="col-12 col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4" style="font-family: 'Poppins', sans-serif;">
                        <div class="services-box">
                            <i class="fa-solid fa-comments"></i>
                            Real-time Messaging
                        </div>
                    </div>
                    <div class="col-12 col-xs-12 col-sm-12 col-md-4 col-lg-4 col-xl-4" style="font-family: 'Poppins', sans-serif;">
                        <div class="services-box">
                            <i class="fa-solid fa-phone"></i>
                            Support
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section id="footer">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <p style="font-weight: 600; color: #fff; margin: 0; padding: 0.5rem 0;text-align:center;user-select:none;">
                            © 2023 - StudyHive
                        </p>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>